### PR TITLE
Replace HTML with native text formatting

### LINKED ISSUE #1229: [BUG] Regression: 17.0.0 RC 1 works, but 17.2.1 RC 2 and newer crashes immediately upon opening the app
**Describe the Bug**
On my device, `Orbot-17.0.0-RC-1-tor.0.4.7.11-fullperm-universal-release` is the last known good build.
`Orbot-17.2.1-RC-2-tor-0.4.8.7-fullperm-universal-release` is the first known bad build.
The latest version, 17.3.2 RC 1, also doesn't work.

Notes:
* I didn't test the beta versions.
* I didn't test the 17.1.0 and 17.1.1 series since I couldn't find a compatible build for my device's architecture for on the [Releases](https://github.com/guardianproject/orbot/releases) page.

**To Reproduce**
1. Uninstall Orbot 
2. Install the latest version of Orbot
3. Tap Orbot in app drawer to open the app
4. The app crashes immediately

**Expected Behavior**
The app should not crash.

**What Custom Configuration Do You Use?**
N/A, I haven't changed any configuration.
I uninstalled Orbot before installing the latest version of Orbot to make sure that it is a clean install.

**Smartphone (please complete the following information):**
- Device: Asus Zenfone 2 Deluxe
- OS: Android 6 (stock ROM)
- Version: `Orbot-17.3.2-RC-1-tor-0.4.8.12-fullperm-universal-release`

**Additional Context**
My device's architecture is x86 / x86-64. I wonder if this may have caused the regression.

### PR DESCRIPTION
**Pull request by meenbeese**
This PR removes the backwards-incompatible text formatting done with HTML throughout the codebase and replaces it with a more native approach that uses a mix of text and graphics APIs like SpannableString, Typeface, etc.

Why This is Better
- Removes `Html.fromHtml()`: No deprecated HTML parsing.
- Native Android Approach: Uses SpannableString.
- Improved Readability & Customization: Easy to add more formatting.

Closes #1229 

Tested on Pixel 8 API 34 Emulator.

### CODE REVIEW

File: app/src/main/java/org/torproject/android/ui/AboutDialogFragment.kt [hunk 1]
```diff
@@ -57,10 +60,12 @@ class AboutDialogFragment : DialogFragment() {
         if (buildAboutText) {
             try {
                 var aboutText = DiskUtils.readFileFromAssets("LICENSE", requireContext())
-                aboutText =
-                    aboutText.replace(ABOUT_LICENSE_EQUALSIGN, "\n").replace("\n\n", "<br/><br/>")
-                        .replace("\n", "")
-                tvAbout.text = Html.fromHtml(aboutText, Html.FROM_HTML_MODE_LEGACY)
+                aboutText = aboutText.replace(ABOUT_LICENSE_EQUALSIGN, "\n").replace("\n\n", "\n\n")
```
Comment (syphyr) [inline app/src/main/java/org/torproject/android/ui/AboutDialogFragment.kt:63]: This line seems strange to me.  Should "\n\n" be replaced with "\n\n"?

**Comment by syphyr** [comment]
error: unable to create symlink app/src/main/assets/LICENSE: File name too long
fatal: cherry-pick failed

**Comment by meenbeese** [comment]
> error: unable to create symlink app/src/main/assets/LICENSE: File name too long fatal: cherry-pick failed

Where are you getting this issue? On the contrary, this PR does not <i>not<i/> symlink to LICENSE anymore.

**Comment by meenbeese** [comment]
> error: unable to create symlink app/src/main/assets/LICENSE: File name too long fatal: cherry-pick failed

Where are you getting this issue? On the contrary, this PR does <i>not</i> symlink to LICENSE anymore.

**Comment by syphyr** [comment]
> > error: unable to create symlink app/src/main/assets/LICENSE: File name too long fatal: cherry-pick failed
> 
> Where are you getting this issue? On the contrary, this PR does not symlink to LICENSE anymore.

just doing a normal cherry pick, I get that error.

git fetch https://github.com/meenbeese/orbot sdk-21-fix && gcp aa74b74b9b08ed825c6ecb97edc6f39549a07e7a

**Comment by meenbeese** [comment]
It is working fine on my machine. Why do you have to cherry-pick? Can't you just checkout the branch?

**Comment by syphyr** [comment]
> It is working fine on my machine. Why do you have to cherry-pick? Can't you just checkout the branch?

I'm really not sure what the problem is. I've never seen this error before when cherry picking. Maybe its a bug in m version of git.

**Comment by syphyr** [comment]
git checkout -b html_fix meenbeese/sdk-21-fix
error: unable to create symlink app/src/main/assets/LICENSE: File name too long
D	app/src/main/assets/LICENSE
Branch 'html_fix' set up to track remote branch 'sdk-21-fix' from 'meenbeese'.
Switched to a new branch 'html_fix

**Comment by syphyr** [comment]
Cant checkout the branch either.

**Comment by syphyr** [comment]
I've fixed it by manually copying the LICENSE file to app/src/main/assets/LICENSE and appending the commit.

It should look like this:

```
diff --git a/app/src/main/assets/LICENSE b/app/src/main/assets/LICENSE
deleted file mode 120000
index 14776154..00000000
--- a/app/src/main/assets/LICENSE
+++ /dev/null
@@ -1 +0,0 @@
-../../../../LICENSE
\ No newline at end of file
diff --git a/app/src/main/assets/LICENSE b/app/src/main/assets/LICENSE
new file mode 100644
index 00000000..ad7d58e9
--- /dev/null
+++ b/app/src/main/assets/LICENSE
@@ -0,0 +1,181 @@
+This file contains the license for Orbot, a free software project to
+provide anonymity on the Internet from a Google Android device.
```

**Comment by syphyr** [comment]
The commit with the problem looks like this:

```
diff --git a/app/src/main/assets/LICENSE b/app/src/main/assets/LICENSE
index 14776154..ad7d58e9 120000
--- a/app/src/main/assets/LICENSE
+++ b/app/src/main/assets/LICENSE
@@ -1 +1,181 @@
-../../../../LICENSE
\ No newline at end of file
+This file contains the license for Orbot, a free software project to
+provide anonymity on the Internet from a Google Android device.
+
+It also lists the licenses for other components used by Orbot, including
+Tor.
```

**Comment by syphyr** [comment]
But, is it really necessary to remove the symlink to LICENSE and copy the file there so it exists twice?

**Comment by syphyr** [comment]
Oh, I see the problem. Your commit should just remove the symlink, but not include the copied file. build.gradle copies the LICENSE file during the build automatically.

**Comment by syphyr** [comment]
Here is a fixed version: https://github.com/syphyr/orbot/commit/3ca2798d126a60ef874673d120d8716428a00b8b

**Comment by meenbeese** [comment]
I don't understand why I shouldn't include the license file in the commit if it is going to be built anyway. Might as well save that step now.

**Comment by meenbeese** [comment]
> But, is it really necessary to remove the symlink to LICENSE and copy the file there so it exists twice?

Yes because symlinking doesn't work in debug mode so the about page was always broken there. Also, this change doesn't add any maintenance burden as the copying over occurs automatically on every build.

**Comment by syphyr** [comment]
This commit should just delete the symlink to the license file because build.gradle copies it to assets during the build processes.  Or, if your intention is to include another copy of the license file to put in assets, then you won't need the additional code added to build.gradle to copy the license file to assets.

**Comment by meenbeese** [comment]
My intention was the former. Updated now to remove the symlink.

**Comment by syphyr** [comment]
> My intention was the former. Updated now to remove the symlink.

Thanks. Just tested it and its working fine now.

**Comment by syphyr** [comment]
`app/src/main/assets/LICENSE` should also be added to .gitignore

**Comment by meenbeese** [comment]
Merge @bitmold ?

**Comment by syphyr** [comment]
The full path to the copied version of the  `LICENSE` file should be used in .gitignore so the original version is also not ignored.
